// src/pages/Homebrew.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useGameData } from '../hooks/useGameData';
import { RaceEditor } from '../components/homebrew/RaceEditor';
import { ClassEditor } from '../components/homebrew/ClassEditor';
import { SpellEditor } from '../components/homebrew/SpellEditor';
import { ItemEditor } from '../components/homebrew/ItemEditor';
import { importHerbs } from '../services/data';
import type { GameRace, GameClass, GameSpell, GameItem } from '../services/storage/database';
import './Homebrew.css';

type Tab = 'races' | 'classes' | 'spells' | 'items';

const SCHOOL_LABELS: Record<string, string> = {
  abjuration: 'Abjuration',
  conjuration: 'Conjuration',
  divination: 'Divination',
  enchantment: 'Enchantement',
  evocation: 'Évocation',
  illusion: 'Illusion',
  necromancy: 'Nécromancie',
  transmutation: 'Transmutation',
};

const CATEGORY_LABELS: Record<string, string> = {
  weapon: 'Arme',
  armor: 'Armure',
  'adventuring-gear': 'Équipement',
  tools: 'Outils',
  'mounts-and-vehicles': 'Montures',
  'magic-item': 'Objet magique',
  herb: 'Herbe',
};

export function Homebrew() {
  const navigate = useNavigate();
  const { races, classes, spells, items, isLoading, refreshData } = useGameData();
  const [activeTab, setActiveTab] = useState<Tab>('races');
  const [editingRace, setEditingRace] = useState<GameRace | null>(null);
  const [editingClass, setEditingClass] = useState<GameClass | null>(null);
  const [editingSpell, setEditingSpell] = useState<GameSpell | null>(null);
  const [editingItem, setEditingItem] = useState<GameItem | null>(null);
  const [isCreatingNew, setIsCreatingNew] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [isImportingHerbs, setIsImportingHerbs] = useState(false);
  const [herbsImportMessage, setHerbsImportMessage] = useState<string | null>(null);

  const handleImportHerbs = async () => {
    setIsImportingHerbs(true);
    setHerbsImportMessage(null);
    try {
      const count = await importHerbs();
      setHerbsImportMessage(`${count} herbes importées avec succès !`);
      await refreshData();
    } catch (error) {
      console.error('Erreur lors de l\'import des herbes:', error);
      setHerbsImportMessage('Erreur lors de l\'import des herbes');
    } finally {
      setIsImportingHerbs(false);
    }
  };

  // Filtres
  const filteredRaces = races.filter((r) =>
    r.name.toLowerCase().includes(searchQuery.toLowerCase())
  );
  const filteredClasses = classes.filter((c) =>
    c.name.toLowerCase().includes(searchQuery.toLowerCase())
  );
  const filteredSpells = spells.filter((s) =>
    s.name.toLowerCase().includes(searchQuery.toLowerCase())
  );
  const filteredItems = items.filter((i) =>
    i.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleCreateRace = () => {
    setEditingRace({
      id: '',
      name: '',
      source: 'Homebrew',
      speed: 30,
      size: 'Medium',
      abilityBonuses: [],
      traits: [],
      languages: ['Common'],
    });
    setIsCreatingNew(true);
  };

  const handleCreateClass = () => {
    setEditingClass({
      id: '',
      name: '',
      source: 'Homebrew',
      hitDie: 8,
      primaryAbility: [],
      savingThrows: [],
      skillChoices: { count: 2, from: [] },
      armorProficiencies: [],
      weaponProficiencies: [],
    });
    setIsCreatingNew(true);
  };

  const handleCreateSpell = () => {
    setEditingSpell({
      id: '',
      name: '',
      source: 'Homebrew',
      level: 1,
      school: 'evocation',
      castingTime: '1 action',
      range: '30 feet',
      components: { verbal: true, somatic: true },
      duration: 'Instantaneous',
      description: '',
      classes: [],
    });
    setIsCreatingNew(true);
  };

  const handleCreateItem = () => {
    setEditingItem({
      id: '',
      name: '',
      source: 'Homebrew',
      category: 'adventuring-gear',
      description: '',
    });
    setIsCreatingNew(true);
  };

  const handleEditRace = (race: GameRace) => {
    setEditingRace({ ...race });
    setIsCreatingNew(false);
  };

  const handleEditClass = (cls: GameClass) => {
    setEditingClass({ ...cls });
    setIsCreatingNew(false);
  };

  const handleEditSpell = (spell: GameSpell) => {
    setEditingSpell({ ...spell });
    setIsCreatingNew(false);
  };

  const handleEditItem = (item: GameItem) => {
    setEditingItem({ ...item });
    setIsCreatingNew(false);
  };

  const handleCloseEditor = () => {
    setEditingRace(null);
    setEditingClass(null);
    setEditingSpell(null);
    setEditingItem(null);
    setIsCreatingNew(false);
  };

  const handleSaveComplete = async () => {
    handleCloseEditor();
    await refreshData();
  };

  if (isLoading) {
    return <div className="loading">Chargement...</div>;
  }

  return (
    <div className="homebrew">
      <header className="homebrew-header">
        <button className="back-button" onClick={() => navigate('/')}>
          ← Retour
        </button>
        <h1>Éditeur de contenu</h1>
      </header>

      <nav className="tabs">
        <button
          className={`tab ${activeTab === 'races' ? 'active' : ''}`}
          onClick={() => setActiveTab('races')}
        >
          Races ({races.length})
        </button>
        <button
          className={`tab ${activeTab === 'classes' ? 'active' : ''}`}
          onClick={() => setActiveTab('classes')}
        >
          Classes ({classes.length})
        </button>
        <button
          className={`tab ${activeTab === 'spells' ? 'active' : ''}`}
          onClick={() => setActiveTab('spells')}
        >
          Sorts ({spells.length})
        </button>
        <button
          className={`tab ${activeTab === 'items' ? 'active' : ''}`}
          onClick={() => setActiveTab('items')}
        >
          Objets ({items.length})
        </button>
      </nav>

      {/* Barre de recherche */}
      <div className="search-bar">
        <input
          type="text"
          placeholder="Rechercher..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </div>

      <div className="content">
        {/* Onglet Races */}
        {activeTab === 'races' && (
          <section className="items-section">
            <div className="section-header">
              <h2>Races</h2>
              <button className="create-button" onClick={handleCreateRace}>
                + Nouvelle race
              </button>
            </div>

            {filteredRaces.length === 0 ? (
              <div className="empty-state">
                <p>{searchQuery ? 'Aucun résultat' : 'Aucune race disponible.'}</p>
                <p className="hint">Importez les données SRD ou créez une race homebrew.</p>
              </div>
            ) : (
              <div className="items-grid">
                {filteredRaces.map((race) => (
                  <div
                    key={race.id}
                    className="item-card"
                    onClick={() => handleEditRace(race)}
                  >
                    <div className="item-header">
                      <h3>{race.name}</h3>
                      <span className={`source-badge ${race.source === 'Homebrew' ? 'homebrew' : 'official'}`}>
                        {race.source}
                      </span>
                    </div>
                    <div className="item-details">
                      <span>Vitesse: {race.speed} ft</span>
                      <span>Taille: {race.size}</span>
                      {race.darkvision && <span>Vision: {race.darkvision} ft</span>}
                    </div>
                    <div className="item-bonuses">
                      {race.abilityBonuses.map((ab, i) => (
                        <span key={i} className="bonus-tag">
                          {ab.ability.slice(0, 3).toUpperCase()} +{ab.bonus}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>
        )}

        {/* Onglet Classes */}
        {activeTab === 'classes' && (
          <section className="items-section">
            <div className="section-header">
              <h2>Classes</h2>
              <button className="create-button" onClick={handleCreateClass}>
                + Nouvelle classe
              </button>
            </div>

            {filteredClasses.length === 0 ? (
              <div className="empty-state">
                <p>{searchQuery ? 'Aucun résultat' : 'Aucune classe disponible.'}</p>
                <p className="hint">Importez les données SRD ou créez une classe homebrew.</p>
              </div>
            ) : (
              <div className="items-grid">
                {filteredClasses.map((cls) => (
                  <div
                    key={cls.id}
                    className="item-card"
                    onClick={() => handleEditClass(cls)}
                  >
                    <div className="item-header">
                      <h3>{cls.name}</h3>
                      <span className={`source-badge ${cls.source === 'Homebrew' ? 'homebrew' : 'official'}`}>
                        {cls.source}
                      </span>
                    </div>
                    <div className="item-details">
                      <span>Dé de vie: d{cls.hitDie}</span>
                      <span>Sauvegardes: {cls.savingThrows.join(', ')}</span>
                    </div>
                    <div className="item-bonuses">
                      {cls.spellcasting && (
                        <span className="bonus-tag spellcaster">
                          Lanceur de sorts
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>
        )}

        {/* Onglet Sorts */}
        {activeTab === 'spells' && (
          <section className="items-section">
            <div className="section-header">
              <h2>Sorts</h2>
              <button className="create-button" onClick={handleCreateSpell}>
                + Nouveau sort
              </button>
            </div>

            {filteredSpells.length === 0 ? (
              <div className="empty-state">
                <p>{searchQuery ? 'Aucun résultat' : 'Aucun sort disponible.'}</p>
                <p className="hint">Importez les données SRD ou créez un sort homebrew.</p>
              </div>
            ) : (
              <div className="items-grid">
                {filteredSpells.map((spell) => (
                  <div
                    key={spell.id}
                    className="item-card"
                    onClick={() => handleEditSpell(spell)}
                  >
                    <div className="item-header">
                      <h3>{spell.name}</h3>
                      <span className={`source-badge ${spell.source === 'Homebrew' ? 'homebrew' : 'official'}`}>
                        {spell.source}
                      </span>
                    </div>
                    <div className="item-details">
                      <span>{spell.level === 0 ? 'Tour de magie' : `Niveau ${spell.level}`}</span>
                      <span>{SCHOOL_LABELS[spell.school] || spell.school}</span>
                    </div>
                    <div className="item-bonuses">
                      {spell.components.verbal && <span className="bonus-tag">V</span>}
                      {spell.components.somatic && <span className="bonus-tag">S</span>}
                      {spell.components.material && <span className="bonus-tag">M</span>}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>
        )}

        {/* Onglet Objets */}
        {activeTab === 'items' && (
          <section className="items-section">
            <div className="section-header">
              <h2>Objets</h2>
              <div className="header-buttons">
                <button
                  className="import-button"
                  onClick={handleImportHerbs}
                  disabled={isImportingHerbs}
                >
                  {isImportingHerbs ? 'Import...' : 'Importer herbes AideDD'}
                </button>
                <button className="create-button" onClick={handleCreateItem}>
                  + Nouvel objet
                </button>
              </div>
            </div>

            {herbsImportMessage && (
              <div className={`import-message ${herbsImportMessage.includes('Erreur') ? 'error' : 'success'}`}>
                {herbsImportMessage}
              </div>
            )}

            {filteredItems.length === 0 ? (
              <div className="empty-state">
                <p>{searchQuery ? 'Aucun résultat' : 'Aucun objet disponible.'}</p>
                <p className="hint">Importez les données SRD ou créez un objet homebrew.</p>
              </div>
            ) : (
              <div className="items-grid">
                {filteredItems.map((item) => (
                  <div
                    key={item.id}
                    className="item-card"
                    onClick={() => handleEditItem(item)}
                  >
                    <div className="item-header">
                      <h3>{item.name}</h3>
                      <span className={`source-badge ${item.source === 'Homebrew' ? 'homebrew' : 'official'}`}>
                        {item.source}
                      </span>
                    </div>
                    <div className="item-details">
                      <span>{CATEGORY_LABELS[item.category] || item.category}</span>
                      {item.cost && <span>{item.cost.quantity} {item.cost.unit}</span>}
                      {item.weight && <span>{item.weight} lb</span>}
                    </div>
                    <div className="item-bonuses">
                      {item.rarity && (
                        <span className="bonus-tag magic">{item.rarity}</span>
                      )}
                      {item.damage && (
                        <span className="bonus-tag">{item.damage.dice} {item.damage.type}</span>
                      )}
                      {item.armorClass && (
                        <span className="bonus-tag">CA {item.armorClass.base}</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>
        )}
      </div>

      {/* Éditeur de race */}
      {editingRace && (
        <RaceEditor
          race={editingRace}
          isNew={isCreatingNew}
          onSave={handleSaveComplete}
          onCancel={handleCloseEditor}
        />
      )}

      {/* Éditeur de classe */}
      {editingClass && (
        <ClassEditor
          gameClass={editingClass}
          isNew={isCreatingNew}
          onSave={handleSaveComplete}
          onCancel={handleCloseEditor}
        />
      )}

      {/* Éditeur de sort */}
      {editingSpell && (
        <SpellEditor
          spell={editingSpell}
          isNew={isCreatingNew}
          onSave={handleSaveComplete}
          onCancel={handleCloseEditor}
        />
      )}

      {/* Éditeur d'objet */}
      {editingItem && (
        <ItemEditor
          item={editingItem}
          isNew={isCreatingNew}
          onSave={handleSaveComplete}
          onCancel={handleCloseEditor}
        />
      )}
    </div>
  );
}

// src/app/features/homebrew/homebrew.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { UpperCasePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatTabsModule } from '@angular/material/tabs';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatBadgeModule } from '@angular/material/badge';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { GameDataState } from '../../core/state/game-data.state';
import { GameDataService } from '../../core/services/game-data.service';
import { SCHOOL_LABELS, CATEGORY_LABELS } from '../../data/labels.data';
import { GameDataEditorDialogComponent, type GameDataEditorDialogData } from './dialogs/game-data-editor-dialog.component';
import { ConfirmDialogComponent, type ConfirmDialogData } from '../../shared/components/confirm-dialog/confirm-dialog.component';
import type { GameRace, GameClass, GameSpell, GameItem } from '../../models/game-data.model';
import { BackButtonComponent } from '../../shared/components/back-button/back-button.component';

@Component({
  selector: 'app-homebrew',
  imports: [
    FormsModule,
    MatTabsModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatCardModule,
    MatChipsModule,
    MatBadgeModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    BackButtonComponent,
    UpperCasePipe,
  ],
  templateUrl: './homebrew.component.html',
  styleUrl: './homebrew.component.scss',
})
export class HomebrewComponent implements OnInit {
  private gameDataState = inject(GameDataState);
  private gameDataService = inject(GameDataService);
  private dialog = inject(MatDialog);
  private snackBar = inject(MatSnackBar);

  // Local state
  readonly searchQuery = signal('');
  readonly isImportingHerbs = signal(false);
  readonly itemCategoryFilter = signal('');
  readonly itemRarityFilter = signal<string | null>(null);

  // Filter options
  readonly itemCategories = [
    { id: 'weapon', label: 'Arme' },
    { id: 'armor', label: 'Armure' },
    { id: 'adventuring-gear', label: 'Équipement' },
    { id: 'tool', label: 'Outil' },
    { id: 'magic-item', label: 'Objet magique' },
    { id: 'consumable', label: 'Consommable' },
    { id: 'herb', label: 'Herbe' },
  ] as const;

  readonly itemRarities = [
    { id: '', label: 'Commun' },
    { id: 'Uncommon', label: 'Peu commun' },
    { id: 'Rare', label: 'Rare' },
    { id: 'Very Rare', label: 'Très rare' },
    { id: 'Legendary', label: 'Légendaire' },
  ] as const;

  // Proxied signals from state
  readonly races = this.gameDataState.races;
  readonly classes = this.gameDataState.classes;
  readonly spells = this.gameDataState.spells;
  readonly items = this.gameDataState.items;
  readonly isLoading = this.gameDataState.isLoading;

  // Labels
  readonly schoolLabels = SCHOOL_LABELS;
  readonly categoryLabels = CATEGORY_LABELS;

  // Filtered computed signals
  readonly filteredRaces = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return this.races();
    return this.races().filter(r =>
      r.name.toLowerCase().includes(query) ||
      r.source.toLowerCase().includes(query),
    );
  });

  readonly filteredClasses = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return this.classes();
    return this.classes().filter(c =>
      c.name.toLowerCase().includes(query) ||
      c.source.toLowerCase().includes(query),
    );
  });

  readonly filteredSpells = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return this.spells();
    return this.spells().filter(s =>
      s.name.toLowerCase().includes(query) ||
      s.source.toLowerCase().includes(query) ||
      s.school.toLowerCase().includes(query),
    );
  });

  readonly filteredItems = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    const category = this.itemCategoryFilter();
    const rarity = this.itemRarityFilter();

    return this.items().filter(i => {
      if (query && !(
        i.name.toLowerCase().includes(query) ||
        i.source.toLowerCase().includes(query) ||
        i.category.toLowerCase().includes(query)
      )) return false;
      if (category && i.category !== category) return false;
      if (rarity !== null && (i.rarity ?? '') !== rarity) return false;
      return true;
    });
  });

  ngOnInit(): void {
    this.gameDataState.loadAll();
  }

  onSearchChange(value: string): void {
    this.searchQuery.set(value);
  }

  toggleCategoryFilter(categoryId: string): void {
    this.itemCategoryFilter.set(this.itemCategoryFilter() === categoryId ? '' : categoryId);
  }

  toggleRarityFilter(rarityId: string): void {
    this.itemRarityFilter.set(this.itemRarityFilter() === rarityId ? null : rarityId);
  }

  // --- Race actions ---

  openRaceEditor(race?: GameRace): void {
    const data: GameDataEditorDialogData = {
      type: 'race',
      item: race ?? this.createDefaultRace(),
      isNew: !race,
    };
    this.openEditor(data);
  }

  // --- Class actions ---

  openClassEditor(gameClass?: GameClass): void {
    const data: GameDataEditorDialogData = {
      type: 'class',
      item: gameClass ?? this.createDefaultClass(),
      isNew: !gameClass,
    };
    this.openEditor(data);
  }

  // --- Spell actions ---

  openSpellEditor(spell?: GameSpell): void {
    const data: GameDataEditorDialogData = {
      type: 'spell',
      item: spell ?? this.createDefaultSpell(),
      isNew: !spell,
    };
    this.openEditor(data);
  }

  // --- Item actions ---

  openItemEditor(item?: GameItem): void {
    const data: GameDataEditorDialogData = {
      type: 'item',
      item: item ?? this.createDefaultItem(),
      isNew: !item,
    };
    this.openEditor(data);
  }

  async importHerbs(): Promise<void> {
    this.isImportingHerbs.set(true);
    try {
      const count = await this.gameDataState.importHerbs();
      this.snackBar.open(`${count} herbes importees depuis AideDD`, 'OK', { duration: 3000 });
    } catch {
      this.snackBar.open('Erreur lors de l\'import des herbes', 'OK', { duration: 3000 });
    } finally {
      this.isImportingHerbs.set(false);
    }
  }

  // --- Helpers ---

  getSchoolLabel(school: string): string {
    return this.schoolLabels[school] ?? school;
  }

  getCategoryLabel(category: string): string {
    return this.categoryLabels[category] ?? category;
  }

  getSpellLevelLabel(level: number): string {
    return level === 0 ? 'Tour de magie' : `Niveau ${level}`;
  }

  getAbilityBonusSummary(bonuses: { ability: string; bonus: number }[]): string {
    return bonuses.map(b => `${b.ability.toUpperCase()} +${b.bonus}`).join(', ');
  }

  // --- Private ---

  private openEditor(data: GameDataEditorDialogData): void {
    const dialogRef = this.dialog.open(GameDataEditorDialogComponent, {
      data,
      width: '600px',
      maxWidth: '95vw',
      maxHeight: '90vh',
    });

    dialogRef.afterClosed().subscribe(async (result: { action: 'save' | 'delete'; item: any } | undefined) => {
      if (!result) return;

      try {
        if (result.action === 'delete') {
          await this.handleDelete(data.type, result.item.id);
        } else if (result.action === 'save') {
          await this.handleSave(data.type, result.item);
        }
        await this.gameDataState.loadAll();
      } catch {
        this.snackBar.open('Erreur lors de la sauvegarde', 'OK', { duration: 3000 });
      }
    });
  }

  private async handleSave(type: string, item: any): Promise<void> {
    switch (type) {
      case 'race':
        await this.gameDataService.saveRace(item);
        this.snackBar.open(`Race "${item.name}" sauvegardee`, 'OK', { duration: 2000 });
        break;
      case 'class':
        await this.gameDataService.saveClass(item);
        this.snackBar.open(`Classe "${item.name}" sauvegardee`, 'OK', { duration: 2000 });
        break;
      case 'spell':
        await this.gameDataService.saveSpell(item);
        this.snackBar.open(`Sort "${item.name}" sauvegarde`, 'OK', { duration: 2000 });
        break;
      case 'item':
        await this.gameDataService.saveItem(item);
        this.snackBar.open(`Objet "${item.name}" sauvegarde`, 'OK', { duration: 2000 });
        break;
    }
  }

  private async handleDelete(type: string, id: string): Promise<void> {
    const confirmRef = this.dialog.open(ConfirmDialogComponent, {
      data: {
        title: 'Supprimer',
        message: 'Voulez-vous vraiment supprimer cet element ?',
        confirmText: 'Supprimer',
        warn: true,
      } as ConfirmDialogData,
    });

    const confirmed = await new Promise<boolean>(resolve => {
      confirmRef.afterClosed().subscribe(result => resolve(!!result));
    });

    if (!confirmed) return;

    switch (type) {
      case 'race':
        await this.gameDataService.deleteRace(id);
        this.snackBar.open('Race supprimee', 'OK', { duration: 2000 });
        break;
      case 'class':
        await this.gameDataService.deleteClass(id);
        this.snackBar.open('Classe supprimee', 'OK', { duration: 2000 });
        break;
      case 'spell':
        await this.gameDataService.deleteSpell(id);
        this.snackBar.open('Sort supprime', 'OK', { duration: 2000 });
        break;
      case 'item':
        await this.gameDataService.deleteItem(id);
        this.snackBar.open('Objet supprime', 'OK', { duration: 2000 });
        break;
    }
  }

  private createDefaultRace(): GameRace {
    return {
      id: crypto.randomUUID().replace(/-/g, ''),
      name: '',
      source: 'Homebrew',
      speed: 30,
      size: 'Medium',
      abilityBonuses: [],
      traits: [],
      languages: ['Commun'],
      description: '',
    };
  }

  private createDefaultClass(): GameClass {
    return {
      id: crypto.randomUUID().replace(/-/g, ''),
      name: '',
      source: 'Homebrew',
      hitDie: 8,
      primaryAbility: [],
      savingThrows: [],
      skillChoices: { count: 2, from: [] },
      armorProficiencies: [],
      weaponProficiencies: [],
      description: '',
    };
  }

  private createDefaultSpell(): GameSpell {
    return {
      id: crypto.randomUUID().replace(/-/g, ''),
      name: '',
      level: 0,
      school: 'evocation',
      castingTime: '1 action',
      range: '18 metres',
      components: { verbal: true, somatic: false },
      duration: 'Instantanee',
      description: '',
      classes: [],
      source: 'Homebrew',
    };
  }

  private createDefaultItem(): GameItem {
    return {
      id: crypto.randomUUID().replace(/-/g, ''),
      name: '',
      source: 'Homebrew',
      category: 'adventuring-gear',
      description: '',
    };
  }
}

<div class="page-container homebrew-page">
  <app-back-button />

  <header class="page-header">
    <h1>Donnees de jeu</h1>
    <mat-form-field appearance="outline" class="search-field">
      <mat-label>Rechercher...</mat-label>
      <mat-icon matPrefix>search</mat-icon>
      <input
        matInput
        [value]="searchQuery()"
        (input)="onSearchChange($any($event.target).value)"
        placeholder="Filtrer par nom, source..."
      />
      @if (searchQuery()) {
        <button matSuffix mat-icon-button (click)="onSearchChange('')">
          <mat-icon>close</mat-icon>
        </button>
      }
    </mat-form-field>
  </header>

  <mat-tab-group animationDuration="200ms" dynamicHeight>
    <!-- Races Tab -->
    <mat-tab>
      <ng-template mat-tab-label>
        <mat-icon>groups</mat-icon>
        <span class="tab-label">Races ({{ filteredRaces().length }})</span>
      </ng-template>

      <div class="tab-content">
        <div class="tab-actions">
          <button mat-flat-button color="primary" (click)="openRaceEditor()">
            <mat-icon>add</mat-icon>
            Nouveau
          </button>
        </div>

        @if (isLoading()) {
          <div class="loading-container">
            <mat-icon class="spinner">hourglass_empty</mat-icon>
            <span>Chargement...</span>
          </div>
        } @else if (filteredRaces().length === 0) {
          <div class="empty-state">
            <mat-icon>groups</mat-icon>
            <p>Aucune race trouvee</p>
          </div>
        } @else {
          <div class="card-grid">
            @for (race of filteredRaces(); track race.id) {
              <mat-card class="data-card" (click)="openRaceEditor(race)">
                <mat-card-header>
                  <mat-card-title>{{ race.name }}</mat-card-title>
                  <span class="source-badge">{{ race.source }}</span>
                </mat-card-header>
                <mat-card-content>
                  <div class="card-details">
                    <span class="detail-chip">
                      <mat-icon>directions_walk</mat-icon>
                      {{ race.speed }} ft
                    </span>
                    <span class="detail-chip">
                      <mat-icon>straighten</mat-icon>
                      {{ race.size }}
                    </span>
                    @if (race.darkvision) {
                      <span class="detail-chip">
                        <mat-icon>visibility</mat-icon>
                        {{ race.darkvision }} ft
                      </span>
                    }
                  </div>
                  @if (race.abilityBonuses.length > 0) {
                    <p class="card-subtitle">{{ getAbilityBonusSummary(race.abilityBonuses) }}</p>
                  }
                  @if (race.traits.length > 0) {
                    <p class="card-traits">{{ race.traits.slice(0, 3).join(', ') }}@if (race.traits.length > 3) {, ...}</p>
                  }
                </mat-card-content>
              </mat-card>
            }
          </div>
        }
      </div>
    </mat-tab>

    <!-- Classes Tab -->
    <mat-tab>
      <ng-template mat-tab-label>
        <mat-icon>shield</mat-icon>
        <span class="tab-label">Classes ({{ filteredClasses().length }})</span>
      </ng-template>

      <div class="tab-content">
        <div class="tab-actions">
          <button mat-flat-button color="primary" (click)="openClassEditor()">
            <mat-icon>add</mat-icon>
            Nouveau
          </button>
        </div>

        @if (isLoading()) {
          <div class="loading-container">
            <mat-icon class="spinner">hourglass_empty</mat-icon>
            <span>Chargement...</span>
          </div>
        } @else if (filteredClasses().length === 0) {
          <div class="empty-state">
            <mat-icon>shield</mat-icon>
            <p>Aucune classe trouvee</p>
          </div>
        } @else {
          <div class="card-grid">
            @for (cls of filteredClasses(); track cls.id) {
              <mat-card class="data-card" (click)="openClassEditor(cls)">
                <mat-card-header>
                  <mat-card-title>{{ cls.name }}</mat-card-title>
                  <span class="source-badge">{{ cls.source }}</span>
                </mat-card-header>
                <mat-card-content>
                  <div class="card-details">
                    <span class="detail-chip">
                      <mat-icon>casino</mat-icon>
                      d{{ cls.hitDie }}
                    </span>
                    @if (cls.spellcasting) {
                      <span class="detail-chip">
                        <mat-icon>auto_fix_high</mat-icon>
                        {{ cls.spellcasting.ability | uppercase }}
                      </span>
                    }
                  </div>
                  @if (cls.savingThrows.length > 0) {
                    <p class="card-subtitle">Sauvegardes: {{ cls.savingThrows.join(', ') | uppercase }}</p>
                  }
                  @if (cls.armorProficiencies.length > 0) {
                    <p class="card-traits">Armures: {{ cls.armorProficiencies.join(', ') }}</p>
                  }
                </mat-card-content>
              </mat-card>
            }
          </div>
        }
      </div>
    </mat-tab>

    <!-- Spells Tab -->
    <mat-tab>
      <ng-template mat-tab-label>
        <mat-icon>auto_fix_high</mat-icon>
        <span class="tab-label">Sorts ({{ filteredSpells().length }})</span>
      </ng-template>

      <div class="tab-content">
        <div class="tab-actions">
          <button mat-flat-button color="primary" (click)="openSpellEditor()">
            <mat-icon>add</mat-icon>
            Nouveau
          </button>
        </div>

        @if (isLoading()) {
          <div class="loading-container">
            <mat-icon class="spinner">hourglass_empty</mat-icon>
            <span>Chargement...</span>
          </div>
        } @else if (filteredSpells().length === 0) {
          <div class="empty-state">
            <mat-icon>auto_fix_high</mat-icon>
            <p>Aucun sort trouve</p>
          </div>
        } @else {
          <div class="card-grid">
            @for (spell of filteredSpells(); track spell.id) {
              <mat-card class="data-card" (click)="openSpellEditor(spell)">
                <mat-card-header>
                  <mat-card-title>{{ spell.name }}</mat-card-title>
                  <span class="source-badge">{{ spell.source }}</span>
                </mat-card-header>
                <mat-card-content>
                  <div class="card-details">
                    <span class="detail-chip">
                      <mat-icon>layers</mat-icon>
                      {{ getSpellLevelLabel(spell.level) }}
                    </span>
                    <span class="detail-chip school-chip">
                      {{ getSchoolLabel(spell.school) }}
                    </span>
                  </div>
                  <div class="card-details">
                    <span class="detail-chip">
                      <mat-icon>schedule</mat-icon>
                      {{ spell.castingTime }}
                    </span>
                    <span class="detail-chip">
                      <mat-icon>straighten</mat-icon>
                      {{ spell.range }}
                    </span>
                  </div>
                  <p class="card-subtitle">
                    @if (spell.components.verbal) {V}
                    @if (spell.components.somatic) { S}
                    @if (spell.components.material) { M}
                    &mdash; {{ spell.duration }}
                  </p>
                </mat-card-content>
              </mat-card>
            }
          </div>
        }
      </div>
    </mat-tab>

    <!-- Items Tab -->
    <mat-tab>
      <ng-template mat-tab-label>
        <mat-icon>inventory_2</mat-icon>
        <span class="tab-label">Objets ({{ filteredItems().length }})</span>
      </ng-template>

      <div class="tab-content">
        <div class="tab-actions">
          <button mat-flat-button color="primary" (click)="openItemEditor()">
            <mat-icon>add</mat-icon>
            Nouveau
          </button>
          <button
            mat-stroked-button
            (click)="importHerbs()"
            [disabled]="isImportingHerbs()"
          >
            <mat-icon>eco</mat-icon>
            @if (isImportingHerbs()) {
              Import en cours...
            } @else {
              Importer herbes AideDD
            }
          </button>
        </div>

        <div class="item-filters">
          <div class="filter-row">
            <span class="filter-label">Catégorie :</span>
            <div class="filter-chips">
              @for (cat of itemCategories; track cat.id) {
                <button
                  class="filter-chip"
                  [class.active]="itemCategoryFilter() === cat.id"
                  (click)="toggleCategoryFilter(cat.id)"
                >{{ cat.label }}</button>
              }
            </div>
          </div>
          <div class="filter-row">
            <span class="filter-label">Rareté :</span>
            <div class="filter-chips">
              @for (r of itemRarities; track r.id) {
                <button
                  class="filter-chip rarity-filter-chip"
                  [class.active]="itemRarityFilter() === r.id"
                  [attr.data-rarity]="r.id || 'common'"
                  (click)="toggleRarityFilter(r.id)"
                >{{ r.label }}</button>
              }
            </div>
          </div>
        </div>

        @if (isLoading()) {
          <div class="loading-container">
            <mat-icon class="spinner">hourglass_empty</mat-icon>
            <span>Chargement...</span>
          </div>
        } @else if (filteredItems().length === 0) {
          <div class="empty-state">
            <mat-icon>inventory_2</mat-icon>
            <p>Aucun objet trouve</p>
          </div>
        } @else {
          <div class="card-grid">
            @for (item of filteredItems(); track item.id) {
              <mat-card class="data-card" (click)="openItemEditor(item)">
                <mat-card-header>
                  <mat-card-title>{{ item.name }}</mat-card-title>
                  <span class="source-badge">{{ item.source }}</span>
                </mat-card-header>
                <mat-card-content>
                  <div class="card-details">
                    <span class="detail-chip category-chip">
                      {{ getCategoryLabel(item.category) }}
                    </span>
                    @if (item.rarity) {
                      <span class="detail-chip rarity-chip" [attr.data-rarity]="item.rarity">
                        {{ item.rarity }}
                      </span>
                    }
                  </div>
                  <div class="card-details">
                    @if (item.damage) {
                      <span class="detail-chip">
                        <mat-icon>gavel</mat-icon>
                        {{ item.damage.dice }} {{ item.damage.type }}
                      </span>
                    }
                    @if (item.armorClass) {
                      <span class="detail-chip">
                        <mat-icon>shield</mat-icon>
                        CA {{ item.armorClass.base }}
                      </span>
                    }
                    @if (item.weight) {
                      <span class="detail-chip">
                        <mat-icon>fitness_center</mat-icon>
                        {{ item.weight }} lb
                      </span>
                    }
                  </div>
                </mat-card-content>
              </mat-card>
            }
          </div>
        }
      </div>
    </mat-tab>
  </mat-tab-group>
</div>
